### ISSUE TITLE
[Setup] Python3 en Linux Subsystem

### ISSUE THREAD

**Issue by jfuentesg26** [IIC2133-PUC/2020-2#59]
[Sistema Operativo] = Windows 10
Hola! Cada vez que ejecuto:  time python3 python/simulate.py tests/hard_test_1.txt test.txt

Me aparece esto:

Traceback (most recent call last):
  File "python/simulate.py", line 3, in <module>
    from mould import Mould
  File "/mnt/c/Users/Usuario/Documents/6TO SEMESTRE 2020-2/Estructura de Datos y Algoritmos/T0-2020-2-jfuentesg26/python/mould.py", line 1, in <module>
    from cell import Cell
  File "/mnt/c/Users/Usuario/Documents/6TO SEMESTRE 2020-2/Estructura de Datos y Algoritmos/T0-2020-2-jfuentesg26/python/cell.py", line 27
        print(f"{idx}:{self.id}", file=file)
                           ^
SyntaxError: invalid syntax

Ya probé actualizar python y sudo, pero nada funciona :(

**Comment by caespinoza5** [comment]
¿Actualizaste `python` o `python3`? Ojo con eso. De todas maneras, puedes cambiar los f-strings de `f"{var1} {var2}"` a `"{} {}".format(var1, var2)` si te acomoda más.
